### ISSUE TITLE
Crash in voronoi.triangles?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-voronoi#11]
https://twitter.com/sifbuilder/status/754771822449614848

**Comment by Fil** [comment]
I noticed this also, one has to do `.extent(null)` before calling `triangles()`
See https://bl.ocks.org/Fil/6c028ce0d9b66d2796bce7f8166f32cd

**Comment by Fil** [comment]
When we add an extent, the Voronoi cells on the boundary of the rectangle have dangling halfedges. Removing those enables `.triangles()` to work as expected (and documented).

```
-         if (i < s0.index && i < s1.index && triangleArea(site, s0, s1) < 0) {
+         if (s0 && s1 && i < s0.index && i < s1.index && triangleArea(site, s0, s1) < 0) {
```

This is consistent with what `.links()` already returns

The documentation could clarify that, in the case of a finite .extent(), what is returned is a subset of the Delaunay triangulation:

```
- Since the Delaunay triangulation is computed as the dual of the Voronoi diagram, and the Voronoi diagram is clipped by the extent, the Delaunay triangulation is likewise affected by the extent.
+ Since the triangulation is computed as the dual of the Voronoi diagram, and the Voronoi diagram is clipped by the extent, a subset of the Delaunay triangulation is returned.
```

I have updated my block (https://bl.ocks.org/Fil/6c028ce0d9b66d2796bce7f8166f32cd) to demonstrate this. (Colors are ugly, but could be a basis for something that we link from the documentation.)

**Comment by Fil** [comment]
An alternative is https://github.com/d3/d3-voronoi/pull/13 (claims to return the "full" Delaunay).

**Comment by Fil** [comment]
Including @adithyaphilip in the discussion.
