### ISSUE TITLE
polygons() returning [null, null, null]

### ISSUE THREAD

**Issue by forresto** [d3/d3-voronoi#20]
I'm missing something, or there is a bug:

```
  const points = [[100, 100], [200, 200], [300, 300]]
  const voronoi = d3.voronoi()
    .extent([0, 0], [400, 400])
  const diagram = voronoi(points)
  const polygons = diagram.polygons()
  console.log(polygons)
```
gives
```
[
  null,
  null,
  null
]
```
without the extent:
```
  const points = [[100, 100], [200, 200], [300, 300]]
  const voronoi = d3.voronoi()
  const diagram = voronoi(points)
  const polygons = diagram.polygons()
  console.log(polygons)
```
gives
```
[
  [
    null
  ],
  [
    null,
    null
  ],
  [
    null
  ]
]
```
😕

**Comment by mbostock** [comment]
Haven’t investigated this yet, but it could be related to cocircular or collinear input sites. (Try jittering the input sites.) If you search the issues you will find some of them to be related.

**Comment by mbostock** [comment]
Also in the first case you are not specifying the extent correctly; you need extra square brackets and to be passing a single extent argument, not passing two arrays as separate arguments. If the extent is all NaN bad things will happen.

**Comment by forresto** [comment]
Thanks! Should `.extend` throw with bad arguments?

This is fun, experimenting with easier edge selection in a dataflow graph:
![screen shot 2016-10-28 at 2 49 18 pm](https://cloud.githubusercontent.com/assets/395307/19820303/c6296e6e-9d26-11e6-8b1e-b4b3eb2c25d4.png)

**Comment by helmuthdu** [comment]
Had this same problem: my mistake was that i was inverting the extends values, ex:

```
const voronoi = d3.voronoi()
    .extent([1796, 847], [30, -67])
```
