### ISSUE TITLE
Missing Triangle?

### ISSUE THREAD

**Issue by thetroy** [d3/d3-voronoi#22]
Discovered this while using triangles() to generate a mesh for interpolating some points. Noticed that some of my points were not inside any triangles. I was surprised to find that a triangle was missing from the mesh. Pruned my data down to 4 vertices, which should yield 2 triangles, but yields just 1. I've tried tweaking the vertices slightly, which results in the expect number of triangles.

```
v = require("d3-voronoi").voronoi();

vertices = [[47.307,105.33],[51.707,104.13],[52.717,110.74],[53.917,106.34]];

console.log(v.triangles(vertices)); // returns 1 triangle

vertices[3][1] += 0.001 // tweak one of the values slightly

console.log(v.triangles(vertices)); // returns 2 triangles (as expected)
```

**Comment by mbostock** [comment]
Looks like you have cocircular points? #12

**Comment by thetroy** [comment]
Thanks for the quick response.

I see that my options are to add some random jitter as suggested in #12 or compute the triangles directly as suggested in #13. I opted for the latter using https://www.npmjs.com/search?q=delaunay-triangulate.
